export interface MetricDetail {
  slug: string; name: string; nameVi: string; description: string;
  formula?: string; whyItMatters: string; relatedMetrics: string[];
}

export const METRICS: MetricDetail[] = [
  { slug:"market-cap",name:"Market Cap",nameVi:"Vốn hóa thị trường",description:"Tổng giá trị thị trường của tất cả cổ phiếu đang lưu hành của một công ty. Được tính bằng giá cổ phiếu nhân với số cổ phiếu lưu hành.",formula:"Giá cổ phiếu × Số cổ phiếu lưu hành",whyItMatters:"Giúp nhà đầu tư đánh giá quy mô công ty và so sánh với các công ty cùng ngành. Công ty có vốn hóa lớn thường ổn định hơn.",relatedMetrics:["volume","pe-ratio","revenue"] },
  { slug:"volume",name:"Volume",nameVi:"Khối lượng giao dịch",description:"Số lượng cổ phiếu được giao dịch trong một khoảng thời gian nhất định. Volume cao cho thấy sự quan tâm lớn của thị trường.",formula:"Tổng số cổ phiếu mua/bán trong phiên",whyItMatters:"Volume cao kèm giá tăng là tín hiệu tích cực. Volume cao kèm giá giảm có thể là tín hiệu xấu.",relatedMetrics:["market-cap","beta"] },
  { slug:"pe-ratio",name:"P/E Ratio",nameVi:"Hệ số P/E",description:"Tỷ lệ giá trên lợi nhuận. Cho biết nhà đầu tư sẵn sàng trả bao nhiêu cho mỗi đồng lợi nhuận.",formula:"Giá cổ phiếu / Lợi nhuận trên cổ phiếu (EPS)",whyItMatters:"P/E cao có thể nghĩa là cổ phiếu đắt hoặc thị trường kỳ vọng tăng trưởng cao. P/E thấp có thể là cơ hội hoặc dấu hiệu rủi ro.",relatedMetrics:["eps","market-cap","revenue"] },
  { slug:"eps",name:"EPS",nameVi:"Lợi nhuận trên cổ phiếu",description:"Phần lợi nhuận ròng phân bổ cho mỗi cổ phiếu đang lưu hành. Là thước đo quan trọng về khả năng sinh lời.",formula:"(Lợi nhuận ròng - Cổ tức ưu đãi) / Số cổ phiếu lưu hành",whyItMatters:"EPS tăng qua các quý cho thấy công ty đang kinh doanh tốt. Là cơ sở để tính P/E.",relatedMetrics:["pe-ratio","net-income","revenue"] },
  { slug:"dividend-yield",name:"Dividend Yield",nameVi:"Tỷ suất cổ tức",description:"Tỷ lệ phần trăm cổ tức hàng năm so với giá cổ phiếu hiện tại.",formula:"Cổ tức hàng năm / Giá cổ phiếu × 100%",whyItMatters:"Thu nhập thụ động cho nhà đầu tư. Tỷ suất cổ tức cao hấp dẫn nhà đầu tư dài hạn.",relatedMetrics:["eps","pe-ratio","free-cash-flow"] },
  { slug:"beta",name:"Beta",nameVi:"Hệ số Beta",description:"Đo lường mức biến động của cổ phiếu so với thị trường chung. Beta > 1 biến động mạnh hơn thị trường.",formula:"Covariance(Ri, Rm) / Variance(Rm)",whyItMatters:"Giúp đánh giá rủi ro. Beta cao = biến động mạnh = tiềm năng lời/lỗ lớn.",relatedMetrics:["volume","52-week-high","52-week-low"] },
  { slug:"52-week-high",name:"52 Week High",nameVi:"Đỉnh 52 tuần",description:"Giá cao nhất của cổ phiếu trong 52 tuần gần nhất. Là mức kháng cự tâm lý quan trọng.",whyItMatters:"Cổ phiếu gần 52-week high có thể đang trong xu hướng tăng mạnh hoặc sắp gặp kháng cự.",relatedMetrics:["52-week-low","beta","volume"] },
  { slug:"52-week-low",name:"52 Week Low",nameVi:"Đáy 52 tuần",description:"Giá thấp nhất của cổ phiếu trong 52 tuần gần nhất. Là mức hỗ trợ tâm lý quan trọng.",whyItMatters:"Cổ phiếu gần 52-week low có thể là cơ hội mua vào hoặc tín hiệu tiếp tục giảm.",relatedMetrics:["52-week-high","beta","volume"] },
  { slug:"revenue",name:"Revenue",nameVi:"Doanh thu",description:"Tổng doanh thu từ hoạt động kinh doanh chính của công ty trước khi trừ chi phí.",whyItMatters:"Doanh thu tăng trưởng ổn định cho thấy công ty có sản phẩm/dịch vụ được thị trường chấp nhận.",relatedMetrics:["net-income","eps","operating-margin"] },
  { slug:"net-income",name:"Net Income",nameVi:"Lợi nhuận ròng",description:"Lợi nhuận còn lại sau khi trừ tất cả chi phí, thuế và lãi vay.",formula:"Doanh thu - Tổng chi phí - Thuế - Lãi vay",whyItMatters:"Là thước đo cuối cùng về khả năng sinh lời thực sự của công ty.",relatedMetrics:["revenue","eps","operating-margin"] },
  { slug:"operating-margin",name:"Operating Margin",nameVi:"Biên lợi nhuận hoạt động",description:"Tỷ lệ lợi nhuận hoạt động trên doanh thu. Cho biết hiệu quả hoạt động kinh doanh.",formula:"Lợi nhuận hoạt động / Doanh thu × 100%",whyItMatters:"Biên lợi nhuận cao cho thấy công ty có lợi thế cạnh tranh và quản lý chi phí tốt.",relatedMetrics:["revenue","net-income","roe"] },
  { slug:"debt-to-equity",name:"Debt to Equity",nameVi:"Tỷ lệ nợ/vốn chủ",description:"Tỷ lệ giữa tổng nợ và vốn chủ sở hữu. Đánh giá mức độ đòn bẩy tài chính.",formula:"Tổng nợ / Vốn chủ sở hữu",whyItMatters:"Tỷ lệ cao có nghĩa công ty phụ thuộc nhiều vào nợ, tăng rủi ro tài chính.",relatedMetrics:["roe","free-cash-flow","net-income"] },
  { slug:"roe",name:"ROE",nameVi:"Tỷ suất sinh lời trên vốn chủ",description:"Đo lường khả năng sinh lời trên mỗi đồng vốn chủ sở hữu.",formula:"Lợi nhuận ròng / Vốn chủ sở hữu × 100%",whyItMatters:"ROE cao cho thấy ban quản lý sử dụng vốn hiệu quả. So sánh với ROE trung bình ngành để đánh giá.",relatedMetrics:["eps","net-income","debt-to-equity"] },
  { slug:"free-cash-flow",name:"Free Cash Flow",nameVi:"Dòng tiền tự do",description:"Dòng tiền còn lại sau khi trừ chi phí vốn. Là tiền thực sự công ty có thể sử dụng.",formula:"Dòng tiền hoạt động - Chi phí vốn",whyItMatters:"FCF dương cho thấy công ty tạo ra tiền mặt thực. Có thể dùng trả cổ tức, mua lại cổ phiếu, hoặc đầu tư.",relatedMetrics:["net-income","dividend-yield","operating-margin"] },
];

export function getMetricBySlug(slug: string): MetricDetail | undefined {
  return METRICS.find((m) => m.slug === slug);
}
